backend = "glx";
paint-on-overlay = true;
vsync = "opengl-swc";
refresh-rate = 60;

# Shadows
shadow = false;
no-dnd-shadow = true;
no-dock-shadow = true;

# Opacity
#blur-kern = "3x3box";

# Fading
fading = true;
fade-in-step = 0.10;
fade-out-step = 0.10;

# GLX options
glx-no-stencil = true;
glx-no-rebind-pixmap = false;
glx-swap-method = 3;
#force-win-blend = true;
