interval=5
border_left=0
border_right=0
border_top=0
border_bottom=3

[brightness]
command=echo 100*$(cat /sys/class/backlight/intel_backlight/brightness)/$(cat /sys/class/backlight/intel_backlight/max_brightness) | bc | awk '{ print " ", $0 }'
border=#8ec07c

[wifi]
command=s=$(iwgetid -r); if [[ $s ]]; then echo $(echo $s; cat /proc/net/wireless | awk 'NR==3 { printf "%.0f", $3*100/70 }') | awk '{ print " ", $0 }'; fi
border=#d3869b

[battery]
command=cat /sys/class/power_supply/BAT0/capacity | awk '{ print " ", $0 }'
border=#83a598

[volume]
command=amixer get Master | awk -F '[][]' 'NR==5 { print " ", $2+0 }'
border=#b8bb26

[date]
command=date '+%d %b' | awk '{ print " ", $0 }'
border=#fabd2f

[time]
command=date +%T | awk '{ print " ", $0 }'
border=#fb4934
