[notebook]
dir = "~/notes"

[note]
language = "en"
default-title = "untitled"
filename = "{{slug title}}-{{id}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 4
id-case = "lower"

[group.journal]
paths = ["journal"]

[group.journal.note]
filename = "{{format-date now '%Y-%m-%d'}}"
template = "journal.md"

[format.markdown]
link-format = "wiki"

[tool]
editor = "nvim"
shell = "bash"
pager = "less -FIRX"
fzf-preview = "bat -p --color=always {-1}"

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"

[filter]
recent = "--sort created- --created-after 'last two weeks'"
journal = "--sort created journal"

[alias]
j = "printf '\n# %s\n' $(date +%H:%M:%S%z) >> $(zk new --no-input -p \"$ZK_NOTEBOOK_DIR\"/journal); zk new --no-input \"$ZK_NOTEBOOK_DIR\"/journal"
