theme = "modus_vivendi"

[editor]
true-color = true
rulers = [81, 121]
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.lsp]
display-inlay-hints = true

[editor.whitespace.render]
space = "none"
tab = "all"
npsp = "none"
nnpsp = "none"
newline = "all"

[editor.whitespace.characters]
space = "·"
tab = "→"
newline = "¬"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1
