bar-list: ["bottom_bar"];

bottom_bar: {
    font: "Adobe Source Code Pro 12";
    position: "bottom";
    height: 20;
    background-color-rgb: 0x000000;

    block-list: ["workspaces", "wifi", "battery", "volume", "date"];
    workspaces: {
        exec: "YABAR_WORKSPACE";
        align: "left";
        internal-option1: "1 2 3 4 5";
        fixed-size: 20;
    }

    wifi: {
        exec: "YABAR_WIFI";
        align: "right";
        internal-prefix: "  ";
        internal-option1: "wlp58s0";
        fixed-size: 150;
    }

    battery: {
        exec: "YABAR_BATTERY";
        align: "right";
        interval: 30;
        internal-option1: "BAT0";
        internal-option2: "    ";
        internal-suffix: "%";
        internal-spacing: true;
    }

    volume: {
        exec: "YABAR_VOLUME";
        align: "right";
        interval: 1;
        internal-option1 : "default Master 0";
        internal-option2 : "mapped";
        internal-option3 : " "
        internal-suffix: "%";
        internal-spacing: true;
    }

    date: {
        exec: "date +'%a %d %b — %T'";
        align: "right";
        type: "periodic";
        interval: 1;
        variable-size: true;
    }
}
